from .comments_component import CommentsComponent
from .chapters_component import ChaptersComponent
from .description_component import DescriptionComponent
from .title_component import TitleComponent
from .manga_type_component import MangaTypeComponent
from .reviews_component import ReviewsComponent
